# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: babaf20b960956b8a68c1f1cf9aab0afa5aa037ea8949b5557f87349a86d9d65cb2edc6419d3bcd09839ccbca9c869422a872a1eb0d76af12a95566a1c40deb0

test:
  secret_key_base: 31331ba3ba7ade6e8910aa6f7baddef3c8ab984ee145335d25a3ff9933d348e5a69e546c2f46d47c72261e828a2b63ab1719b8489c0e14a313b4c5b44bd08c01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
